# Tensor(张量)

## 1.张量的创建
### 基本概念
* PyTorch中将数据封装成了张量
* 张量就是元素为同一数据类型的多维矩阵

In [1]:
import torch
import numpy as np

### 1.1 基本创建方式
1. torch.tensor --> 根据指定数据创建张量
2. torch.Tensor --> 根据形状创建张量
3. torch.IntTensor/FloatTensor/DoubleTensor/... --> 创建指定类型的张量

In [2]:
# 1. torch.tensor
# 1.1 创建标量
data = torch.tensor(10)
print(data)
# 1.2 使用numpy数组来创建张量
data = np.random.randn(2, 3)    # randn(*dimension): 指定array的维度
data = torch.tensor(data)   # float64
print(data)
# 1.3 使用list列表来创建张量
data = [[10., 20., 30.], [10., 20., 30.]]
torch.tensor(data)  # float32
print(data)

tensor(10)
tensor([[ 0.2484, -0.0702, -0.1068],
        [-1.0083, -1.3833, -1.4544]], dtype=torch.float64)
[[10.0, 20.0, 30.0], [10.0, 20.0, 30.0]]


In [3]:
# 2. torch.Tensor
# 2.1 创建一个2x3的张量
data = torch.Tensor(2, 3)
print(data)
# 2.2可以创建指定值的张量
data = torch.Tensor([2, 3])
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2., 3.])


In [4]:
# 3. torch.IntTensor/FloatTensor/DoubleTensor
# 3.1 创建一个int_32类型的张量
data = torch.IntTensor(2, 3)
print(data)
# 3.2 创建一个float_32类型的张量
data = torch.FloatTensor([1, 2, 3])
print(data)
# 3.3 创建一个double(float_64)类型的张量
data = torch.DoubleTensor([1, 2, 3])
print(data)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


### 1.2 线性和随机张量
1. 创建线性张量: torch.arange / torch.linspace
2. 创建随机张量: torch.randn

In [5]:
# 1. 创建线性张量
# 1.1 创建指定步长的张量
data = torch.arange(0, 10, 2)   # arange(start, end, step)
print(data)
# 1.2 在指定区间指定元素个数
data = torch.linspace(0, 10, 100)  # linspace(start, end, num)
print(data)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,

In [6]:
# 2. 创建随机张量
data = torch.randn(2, 3)
print(data)
# 固定随机数
torch.random.manual_seed(123456)
data = torch.randn(2, 3)
print(data)

tensor([[-0.5393, -0.3191, -1.1256],
        [-0.0441, -1.1433, -0.1733]])
tensor([[ 1.8645,  0.4071, -1.1971],
        [ 0.3489, -1.1437, -0.6611]])


### 1.3 创建01张量
1. 创建全1张量: torch.ones / torch.ones_like
2. 创建全0张量: torch.zeros / torch.zeros_like
3. 创建全为指定值张量: torch.full / torch.full_like

In [7]:
# 1. 创建全1张量
data = torch.ones(2, 3)    # ones(*dimension)
print(data)
# 根据其他张量的形状去创建全1张量
data = torch.ones_like(data)
print(data)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# 2. 创建全0张量
data = torch.zeros(2, 3)    # zeros(*dimension)
print(data)
# 根据其他张量的形状去创建全0张量
data = torch.zeros_like(data)
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# 3. 创建全为指定值张量
data = torch.full([2, 3], 10)    # full([dimension], value)
print(data)
# 根据其他张量的形状去创建全为指定值张量
data = torch.full_like(data, 100)
print(data)

tensor([[10, 10, 10],
        [10, 10, 10]])
tensor([[100, 100, 100],
        [100, 100, 100]])


### 1.4 张量元素类型转换
1. tensor.type()
2. torch.double() / torch.float() / torch.int() / ...

In [10]:
# 1. tensor.type()
data = torch.full([2, 3], 10)
print(data.dtype)
data = data.type(torch.DoubleTensor)
print(data.dtype)

torch.int64
torch.float64


In [11]:
# 2. torch.double() / torch.float() / torch.int() / ...
data = torch.full([2, 3], 10)
print(data.dtype)
data = data.double()
print(data.dtype)

torch.int64
torch.float64


## 2.张量的数值计算

### 2.1 基本运算
* 加法: add / add_
* 减法: sub / sub_
* 乘法: mul / mul_
* 除法: div / div_
* 取相反数: neg / neg_

In [12]:
# 1. 不修改原张量数据
data = torch.randint(0, 10, [2, 3]) # randint(start, end, [dimension])
print(data)
data = data.add(10)
print(data)

tensor([[6, 2, 6],
        [0, 1, 8]])
tensor([[16, 12, 16],
        [10, 11, 18]])


In [13]:
# 2. 修改原张量数据
data = torch.randint(0, 10, [2, 3])
print(data)
data.add_(10)
print(data)

tensor([[7, 3, 4],
        [8, 6, 9]])
tensor([[17, 13, 14],
        [18, 16, 19]])


### 2.2 阿达玛积
矩阵对应位置元素相乘

In [14]:
# 1. 使用 mul 函数
data1 = torch.tensor([[1, 2], [3, 4]])
data2 = torch.tensor([[5, 6], [7, 8]])
data = data1.mul(data2)
print(data)

tensor([[ 5, 12],
        [21, 32]])


In [15]:
# 2. 使用 * 运算符
data1 = torch.tensor([[1, 2], [3, 4]])
data2 = torch.tensor([[5, 6], [7, 8]])
data = data1 * data2
print(data)

tensor([[ 5, 12],
        [21, 32]])


### 2.3 矩阵乘法
1. @ 运算符
2. mm: 2维张量的矩阵乘法
3. bmm: 3维张量的批次矩阵乘法
4. matmul: 对张量形状没有限定, 如果形状不同, 用最后几个维度进行矩阵乘法

In [16]:
# 1. 使用 @ 运算符
data1 = torch.tensor([[1, 2], 
                      [3, 4], 
                      [5, 6]])
data2 = torch.tensor([[5, 6], 
                      [7, 8]])
data = data1 @ data2
print(data)

tensor([[19, 22],
        [43, 50],
        [67, 78]])


In [17]:
# 2. 使用 mm 函数
data1 = torch.tensor([[1, 2], 
                      [3, 4], 
                      [5, 6]])
data2 = torch.tensor([[5, 6], 
                      [7, 8]])
data = torch.mm(data1, data2)
print(data)

tensor([[19, 22],
        [43, 50],
        [67, 78]])


In [18]:
# 3. 使用 bmm 函数
data1 = torch.randn(3, 4, 5)    # randn(batch, row, col)
data2 = torch.randn(3, 5, 8)
data = torch.bmm(data1, data2)
print(data.shape)

torch.Size([3, 4, 8])


In [19]:
# 4. 使用 matmul 函数
data1 = torch.randn(4, 5)
data2 = torch.randn(5, 8)
print(torch.matmul(data1, data2).shape)

data1 = torch.randn(3, 4, 5)
data2 = torch.randn(3, 5, 8)
print(torch.matmul(data1, data2).shape)

torch.Size([4, 8])
torch.Size([3, 4, 8])


### 2.4 指定运算设备
#### 将计算移动到GPU上的方法
* 使用cuda方法
* 直接在GPU上创建张量
* 使用.to()方法指定设备

In [20]:
# 1. 使用 cuda 方法
data = torch.tensor([10, 20, 30])
print(data.device)
data.cuda() if torch.cuda.is_available() else data.cpu()

cpu


tensor([10, 20, 30])

In [21]:
# 2. 直接在GPU上创建张量
if torch.cuda.is_available():
    data = torch.tensor([10, 20, 30], device='cuda')
    print(data.device)

In [22]:
# 3. 使用 .to() 方法指定设备
data = torch.tensor([10, 20, 30])
print(data.device)
data = data.to('cuda') if torch.cuda.is_available() else data.to('cpu')
print(data.device)

cpu
cpu


## 3.张量的类型转换

### 3.1 张量转换为numpy数组
使用Tensor.numpy()方法，但是会共享内存，可以通过copy()函数规避

In [23]:
# 1. 张量转换为numpy数组
data_tensor = torch.tensor([2, 3, 4])
data_np = data_tensor.numpy()
print(type(data_tensor))
print(type(data_np))
# 2. 共享内存
data_tensor[1] = 4
data_np[2] = 6
print(data_tensor)
print(data_np)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2, 4, 6])
[2 4 6]


In [24]:
# 3. 规避共享内存
data_np = data_tensor.numpy().copy()
data_tensor[0] = 20
print(data_tensor)
print(data_np)

tensor([20,  4,  6])
[2 4 6]


### 3.2 numpy数组转换为张量
1. 使用torch.from_numpy()方法，默认共享内存，可以通过copy()函数规避
2. 使用torch.tensor()方法，默认不共享内存

In [25]:
# 1. from_numpy()
data_np = np.array([2, 3, 4])
data_tensor = torch.from_numpy(data_np)
data_np[1] = 4
data_tensor[2] = 6
print(data_tensor)
print(data_np)

tensor([2, 4, 6], dtype=torch.int32)
[2 4 6]


In [26]:
# 2. tensor()
data_np = np.array([2, 3, 4])
data_tensor = torch.tensor(data_np)
data_np[1] = 4
data_tensor[2] = 6
print(data_tensor)
print(data_np)

tensor([2, 3, 6], dtype=torch.int32)
[2 4 4]


### 3.3 标量张量和数字的转换

In [27]:
# 提取含有单个元素的张量的值: tensor.item()
tensor1 = torch.tensor(30)
tensor2 = torch.tensor([30])
tensor3 = torch.tensor([[30]])

print(tensor1.item())
print(tensor2.item())
print(tensor3.item())

30
30
30


## 4.张量的拼接

### 4.1 torch.cat()

In [28]:
torch.manual_seed(0)
data1 = torch.randint(0, 10, [3, 4, 5])
data2 = torch.randint(0, 10, [3, 4, 5])
print(data1.shape)
print(data2.shape)
# 1. 按0维度拼接
data = torch.cat([data1, data2], dim=0) # torch.cat(tensors, dim=dimension)
print(data.shape)
# 2. 按1维度拼接
data = torch.cat([data1, data2], dim=1)
print(data.shape)

torch.Size([3, 4, 5])
torch.Size([3, 4, 5])
torch.Size([6, 4, 5])
torch.Size([3, 8, 5])


### 4.2 torch.stack()

In [29]:
torch.manual_seed(0)
data1 = torch.randint(0, 10, [2, 3])
data2 = torch.randint(0, 10, [2, 3])
print(data1)
print(data2)
print('-' * 30)
# 将两个张量叠加(stack)
# 按0维度叠加(整体叠加)
data = torch.stack([data1, data2], dim=0)
print(data.shape)
print(data)
print('-' * 30)
# 按1维度叠加(按行叠加)
data = torch.stack([data1, data2], dim=1)
print(data.shape)
print(data)
print('-' * 30)
# 按2维度叠加(按元素叠加)
data = torch.stack([data1, data2], dim=2)
print(data.shape)
print(data)

tensor([[4, 9, 3],
        [0, 3, 9]])
tensor([[7, 3, 7],
        [3, 1, 6]])
------------------------------
torch.Size([2, 2, 3])
tensor([[[4, 9, 3],
         [0, 3, 9]],

        [[7, 3, 7],
         [3, 1, 6]]])
------------------------------
torch.Size([2, 2, 3])
tensor([[[4, 9, 3],
         [7, 3, 7]],

        [[0, 3, 9],
         [3, 1, 6]]])
------------------------------
torch.Size([2, 3, 2])
tensor([[[4, 7],
         [9, 3],
         [3, 7]],

        [[0, 3],
         [3, 1],
         [9, 6]]])


## 5.张量索引操作

### 5.1 简单行列索引

In [30]:
torch.manual_seed(0)
data = torch.randint(0, 10, [4, 5])
print(data)
print('-' * 30)
# 1. 获得指定行元素
print(data[0])
# 2. 获得指定列元素
print(data[:, 2])   # :表示所有行, 2表示第3列
# : 的使用
print('-' * 30)
print(data[:, :])
print(data[:3, :2])
print('-' * 30)
# 3. 获得指定元素
print(data[1, 2], data[1][2])

tensor([[4, 9, 3, 0, 3],
        [9, 7, 3, 7, 3],
        [1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3]])
------------------------------
tensor([4, 9, 3, 0, 3])
tensor([3, 3, 6, 8])
------------------------------
tensor([[4, 9, 3, 0, 3],
        [9, 7, 3, 7, 3],
        [1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3]])
tensor([[4, 9],
        [9, 7],
        [1, 6]])
------------------------------
tensor(3) tensor(3)


### 5.2 列表索引

In [31]:
torch.manual_seed(0)
data = torch.randint(0, 10, [4, 5])
print(data)
print('-' * 30)
# 1. 一维列表索引
print(data[[0, 2, 3], [0, 1, 2]])   # 表示获得data[0, 0], data[2, 1], data[3, 2]
# 2. 二维列表索引
print(data[[[0], [2], [3]], [0, 1, 2]])     # 表示获得第0行的第0, 1, 2列元素, 第2行的第0, 1, 2列元素, 第3行的第0, 1, 2列元素

tensor([[4, 9, 3, 0, 3],
        [9, 7, 3, 7, 3],
        [1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3]])
------------------------------
tensor([4, 6, 8])
tensor([[4, 9, 3],
        [1, 6, 6],
        [6, 6, 8]])


### 5.3 布尔索引

In [32]:
torch.manual_seed(0)
data = torch.randint(0, 10, [4, 5])
print(data)
print('-' * 30)
# 1. 获得大于5的元素
print(data > 5)
print(data[data > 5])

tensor([[4, 9, 3, 0, 3],
        [9, 7, 3, 7, 3],
        [1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3]])
------------------------------
tensor([[False,  True, False, False, False],
        [ True,  True, False,  True, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True, False, False]])
tensor([9, 9, 7, 7, 6, 6, 9, 8, 6, 6, 8])


### 5.4 多维索引

In [33]:
torch.manual_seed(0)
data = torch.randint(0, 10, [3, 4, 5])
print(data)
print('-' * 30)
# 1. 获得第0个batch的第0, 1, 2行的第0, 1, 2, 3列元素
print(data[0, :3, :4])

tensor([[[4, 9, 3, 0, 3],
         [9, 7, 3, 7, 3],
         [1, 6, 6, 9, 8],
         [6, 6, 8, 4, 3]],

        [[6, 9, 1, 4, 4],
         [1, 9, 9, 9, 0],
         [1, 2, 3, 0, 5],
         [5, 2, 9, 1, 8]],

        [[8, 3, 6, 9, 1],
         [7, 3, 5, 2, 1],
         [0, 9, 3, 1, 1],
         [0, 3, 6, 6, 7]]])
------------------------------
tensor([[4, 9, 3, 0],
        [9, 7, 3, 7],
        [1, 6, 6, 9]])


## 6.张量的形状操作

### 6.1 reshape函数

In [34]:
torch.manual_seed(0)
data = torch.randint(0, 10, [4, 5])
print(data.shape)
new_data = data.reshape(2, 10)
print(new_data)
# 注意: 转换前后元素个数相同, 不能少也不能多
new_data = data.reshape(5, -1)
print(new_data)

torch.Size([4, 5])
tensor([[4, 9, 3, 0, 3, 9, 7, 3, 7, 3],
        [1, 6, 6, 9, 8, 6, 6, 8, 4, 3]])
tensor([[4, 9, 3, 0],
        [3, 9, 7, 3],
        [7, 3, 1, 6],
        [6, 9, 8, 6],
        [6, 8, 4, 3]])


### 6.2 transpose和permute函数

In [35]:
# 1. transpose函数
torch.manual_seed(0)
data = torch.randint(0, 10, [3, 4, 5])
print(data.shape)
new_data = data.transpose(1, 2)      # 交换第1维和第2维
print(new_data.shape)
# 缺点: 一次只能交换一对维度

torch.Size([3, 4, 5])
torch.Size([3, 5, 4])


In [36]:
# 2. permute函数
torch.manual_seed(0)
data = torch.randint(0, 10, [3, 4, 5])
print(data.shape)
new_data = data.permute(1, 2, 0)    # 第1维, 第2维, 第0维
print(new_data.shape)

torch.Size([3, 4, 5])
torch.Size([4, 5, 3])


### 6.3 view和contiguous函数

In [37]:
# 1. view函数
torch.manual_seed(0)
data = torch.tensor([[10, 20, 30],
                    [40, 50, 60]])
print(data.shape)
if data.is_contiguous():    # 判断是否为连续内存
    new_data = data.view(3, 2)
    print(new_data.shape)
# 2. 注意: 当张量经过 transpose 和 permute 操作后, 其内存布局可能发生变化, 导致 view 操作失效
# 3. 解决办法: 使用 contiguous 函数, 使张量变为连续内存
new_data = data.transpose(0, 1)
print(new_data.is_contiguous())
new_data = new_data.contiguous().view(2, 3)
print(new_data.shape)

torch.Size([2, 3])
torch.Size([3, 2])
False
torch.Size([2, 3])


### 6.4 squeeze和unsqueeze函数

In [38]:
# 1. squeeze函数: 去掉所有长度为1的维度
torch.manual_seed(0)
data = torch.randint(0, 10, [1, 2, 1, 3, 1])
print(data.shape)
new_data = data.squeeze()
print(new_data.shape)

torch.Size([1, 2, 1, 3, 1])
torch.Size([2, 3])


In [39]:
# 2. unsqueeze函数: 在指定位置增加长度为1的维度
torch.manual_seed(0)
data = torch.randint(0, 10, [3, 5])
print(data.shape)
new_data = data.unsqueeze(1)    # 在第1维增加长度为1的维度, -1表示在最后一个维度增加
print(new_data.shape)

torch.Size([3, 5])
torch.Size([3, 1, 5])


## 7.张量运算函数

In [41]:
# 1. 计算均值
torch.manual_seed(0)
data = torch.randint(0, 10, [2, 3], dtype=torch.float64)
print(data)
# 默认求所有元素的均值
print(data.mean())
# 按指定维度求均值
print(data.mean(dim=0))
print(data.mean(dim=1))

tensor([[4., 9., 3.],
        [0., 3., 9.]], dtype=torch.float64)
tensor(4.6667, dtype=torch.float64)
tensor([2., 6., 6.], dtype=torch.float64)
tensor([5.3333, 4.0000], dtype=torch.float64)


In [42]:
# 2. 求和
torch.manual_seed(0)
data = torch.randint(0, 10, [2, 3]).double()
print(data)
print(data.sum())
print(data.sum(dim=0))
print(data.sum(dim=1))

tensor([[4., 9., 3.],
        [0., 3., 9.]], dtype=torch.float64)
tensor(28., dtype=torch.float64)
tensor([ 4., 12., 12.], dtype=torch.float64)
tensor([16., 12.], dtype=torch.float64)


In [43]:
# 3. 平方
torch.manual_seed(0)
data = torch.randint(0, 10, [2, 3]).double()
print(data)
print(data.pow(2))

tensor([[4., 9., 3.],
        [0., 3., 9.]], dtype=torch.float64)
tensor([[16., 81.,  9.],
        [ 0.,  9., 81.]], dtype=torch.float64)


In [44]:
# 4. 平方根
torch.manual_seed(0)
data = torch.randint(0, 10, [2, 3]).double()
print(data)
print(data.sqrt())

tensor([[4., 9., 3.],
        [0., 3., 9.]], dtype=torch.float64)
tensor([[2.0000, 3.0000, 1.7321],
        [0.0000, 1.7321, 3.0000]], dtype=torch.float64)


In [45]:
# 5. exp
torch.manual_seed(0)
data = torch.randint(0, 10, [2, 3]).double()
print(data)
print(data.exp())

tensor([[4., 9., 3.],
        [0., 3., 9.]], dtype=torch.float64)
tensor([[5.4598e+01, 8.1031e+03, 2.0086e+01],
        [1.0000e+00, 2.0086e+01, 8.1031e+03]], dtype=torch.float64)


In [46]:
# 6. 取对数
torch.manual_seed(0)
data = torch.randint(0, 10, [2, 3]).double()
print(data)
print(data.log())   # 默认使用自然对数
print(data.log2())
print(data.log10())

tensor([[4., 9., 3.],
        [0., 3., 9.]], dtype=torch.float64)
tensor([[1.3863, 2.1972, 1.0986],
        [  -inf, 1.0986, 2.1972]], dtype=torch.float64)
tensor([[2.0000, 3.1699, 1.5850],
        [  -inf, 1.5850, 3.1699]], dtype=torch.float64)
tensor([[0.6021, 0.9542, 0.4771],
        [  -inf, 0.4771, 0.9542]], dtype=torch.float64)


## 8.自动微分模块

### 8.1 梯度基本运算

In [48]:
# 1. 标量的梯度计算
x = torch.tensor(10, requires_grad=True, dtype=torch.float64)   # 对于需要求导的张量, 必须设置 requires_grad=True
y = x ** 2 + 20
# 自动微分
y.backward()
# 访问梯度
print(x.grad)

tensor(20., dtype=torch.float64)


In [50]:
# 2. 向量的梯度计算
x = torch.tensor([10, 20, 30, 40], requires_grad=True, dtype=torch.float64)
y1 = x ** 2 + 20
# 注意: 自动微分的对象必须是标量
y2 = y1.mean()
# 自动微分
y2.backward()
# 访问梯度
print(x.grad)

tensor([ 5., 10., 15., 20.], dtype=torch.float64)


In [52]:
# 3. 多标量的梯度计算
x1 = torch.tensor(10, requires_grad=True, dtype=torch.float64)
x2 = torch.tensor(20, requires_grad=True, dtype=torch.float64)
y = x1 ** 2 + x2 ** 2 + x1 * x2
y.backward()
print(x1.grad)
print(x2.grad)

tensor(40., dtype=torch.float64)
tensor(50., dtype=torch.float64)


In [53]:
# 4. 多向量的梯度计算
x1 = torch.tensor([10, 20], requires_grad=True, dtype=torch.float64)
x2 = torch.tensor([30, 40], requires_grad=True, dtype=torch.float64)
y = x1 ** 2 + x2 ** 2 + x1 * x2
y = y.sum()
y.backward()
print(x1.grad)
print(x2.grad)

tensor([50., 80.], dtype=torch.float64)
tensor([ 70., 100.], dtype=torch.float64)


### 8.2 控制梯度计算

In [54]:
# 1. 控制梯度计算
x = torch.tensor(10, requires_grad=True, dtype=torch.float64)
print(x.requires_grad)
# 法一
with torch.no_grad():
    y = x ** 2
print(y.requires_grad)
# 法二
@torch.no_grad()
def func(x):
    return x ** 2
y = func(x)
print(y.requires_grad)
# 法三: 全局设置
torch.set_grad_enabled(False)
y = x ** 2
print(y.requires_grad)

True
False
False
False


In [56]:
# 2. 累计梯度和梯度清零
torch.set_grad_enabled(True)
x = torch.tensor([10, 20 ,30, 40], requires_grad=True, dtype=torch.float64)
# 当重复对x进行梯度计算时, 会将之前的梯度累计到x.grad中
for _ in range(3):
    f1 = x ** 2 + 20
    f2 = f1.mean()
    # 梯度清零
    if x.grad is not None:
        x.grad.data.zero_()
    f2.backward()
    print(x.grad)

tensor([ 5., 10., 15., 20.], dtype=torch.float64)
tensor([ 5., 10., 15., 20.], dtype=torch.float64)
tensor([ 5., 10., 15., 20.], dtype=torch.float64)


In [59]:
# example: 梯度下降优化函数
x = torch.tensor(10, requires_grad=True, dtype=torch.float64)
for _ in range(5000):
    # 正向计算
    y = x ** 2
    # 梯度清零
    if x.grad is not None:
        x.grad.data.zero_()
    # 反向传播
    y.backward()
    # 更新参数
    x.data -= 0.01 * x.grad
    print(x.data)

tensor(9.8000, dtype=torch.float64)
tensor(9.6040, dtype=torch.float64)
tensor(9.4119, dtype=torch.float64)
tensor(9.2237, dtype=torch.float64)
tensor(9.0392, dtype=torch.float64)
tensor(8.8584, dtype=torch.float64)
tensor(8.6813, dtype=torch.float64)
tensor(8.5076, dtype=torch.float64)
tensor(8.3375, dtype=torch.float64)
tensor(8.1707, dtype=torch.float64)
tensor(8.0073, dtype=torch.float64)
tensor(7.8472, dtype=torch.float64)
tensor(7.6902, dtype=torch.float64)
tensor(7.5364, dtype=torch.float64)
tensor(7.3857, dtype=torch.float64)
tensor(7.2380, dtype=torch.float64)
tensor(7.0932, dtype=torch.float64)
tensor(6.9514, dtype=torch.float64)
tensor(6.8123, dtype=torch.float64)
tensor(6.6761, dtype=torch.float64)
tensor(6.5426, dtype=torch.float64)
tensor(6.4117, dtype=torch.float64)
tensor(6.2835, dtype=torch.float64)
tensor(6.1578, dtype=torch.float64)
tensor(6.0346, dtype=torch.float64)
tensor(5.9140, dtype=torch.float64)
tensor(5.7957, dtype=torch.float64)
tensor(5.6798, dtype=torch.f

### 8.3 注意事项
当对设置了 requires_grad=True 的张量使用 numpy 函数进行转换时, 会出现如下报错:

`Can't call numpy() on Tensor that requires grad. Use torch.detach().numpy() instead.`

此时, 应该使用 torch.detach() 函数将张量进行分离, 然后再使用 numpy() 函数进行转换.

In [60]:
x = torch.tensor([10, 20], requires_grad=True, dtype=torch.float64)
print(x.numpy())   # 报错

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [63]:
# x是叶子节点
x = torch.tensor([10, 20], requires_grad=True, dtype=torch.float64)
# 使用 detach() 函数分离出一个新的张量
x_detached = x.detach()
# x_detached 和 x 共享内存, 所以 x 的任何计算都会影响到对 x_detached 的梯度计算
print(id(x_detached.data) == id(x.data))
# 但是 x_detached 不能进行梯度计算, 所以对 x_detached 的任何操作都不会影响到 x 的梯度计算
print(x_detached.requires_grad)

True
False
