# Tensor(张量)

## 1.张量的创建
### 基本概念
* PyTorch中将数据封装成了张量
* 张量就是元素为同一数据类型的多维矩阵

In [1]:
import torch
import numpy as np

### 1.1 基本创建方式
1. torch.tensor --> 根据指定数据创建张量
2. torch.Tensor --> 根据形状创建张量
3. torch.IntTensor/FloatTensor/DoubleTensor/... --> 创建指定类型的张量

In [2]:
# 1. torch.tensor
# 1.1 创建标量
data = torch.tensor(10)
print(data)
# 1.2 使用numpy数组来创建张量
data = np.random.randn(2, 3)    # randn(*dimension): 指定array的维度
data = torch.tensor(data)   # float64
print(data)
# 1.3 使用list列表来创建张量
data = [[10., 20., 30.], [10., 20., 30.]]
torch.tensor(data)  # float32
print(data)

tensor(10)
tensor([[-0.7602, -0.8465, -0.7995],
        [-1.0257,  0.3217, -0.7513]], dtype=torch.float64)
[[10.0, 20.0, 30.0], [10.0, 20.0, 30.0]]


In [3]:
# 2. torch.Tensor
# 2.1 创建一个2x3的张量
data = torch.Tensor(2, 3)
print(data)
# 2.2可以创建指定值的张量
data = torch.Tensor([2, 3])
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2., 3.])


In [4]:
# 3. torch.IntTensor/FloatTensor/DoubleTensor
# 3.1 创建一个int_32类型的张量
data = torch.IntTensor(2, 3)
print(data)
# 3.2 创建一个float_32类型的张量
data = torch.FloatTensor([1, 2, 3])
print(data)
# 3.3 创建一个double(float_64)类型的张量
data = torch.DoubleTensor([1, 2, 3])
print(data)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


### 1.2 线性和随机张量
1. 创建线性张量: torch.arange / torch.linspace
2. 创建随机张量: torch.randn

In [5]:
# 1. 创建线性张量
# 1.1 创建指定步长的张量
data = torch.arange(0, 10, 2)   # arange(start, end, step)
print(data)
# 1.2 在指定区间指定元素个数
data = torch.linspace(0, 10, 100)  # linspace(start, end, num)
print(data)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,

In [6]:
# 2. 创建随机张量
data = torch.randn(2, 3)
print(data)
# 固定随机数
torch.random.manual_seed(123456)
data = torch.randn(2, 3)
print(data)

tensor([[-0.6238,  0.6304,  1.5717],
        [ 1.2786, -0.0621,  0.4617]])
tensor([[ 1.8645,  0.4071, -1.1971],
        [ 0.3489, -1.1437, -0.6611]])


### 1.3 创建01张量
1. 创建全1张量: torch.ones / torch.ones_like
2. 创建全0张量: torch.zeros / torch.zeros_like
3. 创建全为指定值张量: torch.full / torch.full_like

In [7]:
# 1. 创建全1张量
data = torch.ones(2, 3)    # ones(*dimension)
print(data)
# 根据其他张量的形状去创建全1张量
data = torch.ones_like(data)
print(data)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# 2. 创建全0张量
data = torch.zeros(2, 3)    # zeros(*dimension)
print(data)
# 根据其他张量的形状去创建全0张量
data = torch.zeros_like(data)
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# 3. 创建全为指定值张量
data = torch.full([2, 3], 10)    # full([dimension], value)
print(data)
# 根据其他张量的形状去创建全为指定值张量
data = torch.full_like(data, 100)
print(data)

tensor([[10, 10, 10],
        [10, 10, 10]])
tensor([[100, 100, 100],
        [100, 100, 100]])


### 1.4 张量元素类型转换
1. tensor.type()
2. torch.double() / torch.float() / torch.int() / ...

In [10]:
# 1. tensor.type()
data = torch.full([2, 3], 10)
print(data.dtype)
data = data.type(torch.DoubleTensor)
print(data.dtype)

torch.int64
torch.float64


In [11]:
# 2. torch.double() / torch.float() / torch.int() / ...
data = torch.full([2, 3], 10)
print(data.dtype)
data = data.double()
print(data.dtype)

torch.int64
torch.float64


## 2.张量的数值计算

### 2.1 基本运算
* 加法: add / add_
* 减法: sub / sub_
* 乘法: mul / mul_
* 除法: div / div_
* 取相反数: neg / neg_

In [12]:
# 1. 不修改原张量数据
data = torch.randint(0, 10, [2, 3]) # randint(start, end, [dimension])
print(data)
data = data.add(10)
print(data)

tensor([[6, 2, 6],
        [0, 1, 8]])
tensor([[16, 12, 16],
        [10, 11, 18]])


In [13]:
# 2. 修改原张量数据
data = torch.randint(0, 10, [2, 3])
print(data)
data.add_(10)
print(data)

tensor([[7, 3, 4],
        [8, 6, 9]])
tensor([[17, 13, 14],
        [18, 16, 19]])


### 2.2 阿达玛积
矩阵对应位置元素相乘

In [14]:
# 1. 使用 mul 函数
data1 = torch.tensor([[1, 2], [3, 4]])
data2 = torch.tensor([[5, 6], [7, 8]])
data = data1.mul(data2)
print(data)

tensor([[ 5, 12],
        [21, 32]])


In [15]:
# 2. 使用 * 运算符
data1 = torch.tensor([[1, 2], [3, 4]])
data2 = torch.tensor([[5, 6], [7, 8]])
data = data1 * data2
print(data)

tensor([[ 5, 12],
        [21, 32]])


### 2.3 矩阵乘法
1. @ 运算符
2. mm: 2维张量的矩阵乘法
3. bmm: 3维张量的批次矩阵乘法
4. matmul: 对张量形状没有限定, 如果形状不同, 用最后几个维度进行矩阵乘法

In [16]:
# 1. 使用 @ 运算符
data1 = torch.tensor([[1, 2], 
                      [3, 4], 
                      [5, 6]])
data2 = torch.tensor([[5, 6], 
                      [7, 8]])
data = data1 @ data2
print(data)

tensor([[19, 22],
        [43, 50],
        [67, 78]])


In [17]:
# 2. 使用 mm 函数
data1 = torch.tensor([[1, 2], 
                      [3, 4], 
                      [5, 6]])
data2 = torch.tensor([[5, 6], 
                      [7, 8]])
data = torch.mm(data1, data2)
print(data)

tensor([[19, 22],
        [43, 50],
        [67, 78]])


In [18]:
# 3. 使用 bmm 函数
data1 = torch.randn(3, 4, 5)    # randn(batch, row, col)
data2 = torch.randn(3, 5, 8)
data = torch.bmm(data1, data2)
print(data.shape)

torch.Size([3, 4, 8])


In [19]:
# 4. 使用 matmul 函数
data1 = torch.randn(4, 5)
data2 = torch.randn(5, 8)
print(torch.matmul(data1, data2).shape)

data1 = torch.randn(3, 4, 5)
data2 = torch.randn(3, 5, 8)
print(torch.matmul(data1, data2).shape)

torch.Size([4, 8])
torch.Size([3, 4, 8])


### 2.4 指定运算设备
#### 将计算移动到GPU上的方法
* 使用cuda方法
* 直接在GPU上创建张量
* 使用.to()方法指定设备

In [20]:
# 1. 使用 cuda 方法
data = torch.tensor([10, 20, 30])
print(data.device)
data.cuda() if torch.cuda.is_available() else data.cpu()

cpu


tensor([10, 20, 30])

In [21]:
# 2. 直接在GPU上创建张量
if torch.cuda.is_available():
    data = torch.tensor([10, 20, 30], device='cuda')
    print(data.device)

In [22]:
# 3. 使用 .to() 方法指定设备
data = torch.tensor([10, 20, 30])
print(data.device)
data = data.to('cuda') if torch.cuda.is_available() else data.to('cpu')
print(data.device)

cpu
cpu


## 3.张量的类型转换

### 3.1 张量转换为numpy数组
使用Tensor.numpy()方法，但是会共享内存，可以通过copy()函数规避

In [24]:
# 1. 张量转换为numpy数组
data_tensor = torch.tensor([2, 3, 4])
data_np = data_tensor.numpy()
print(type(data_tensor))
print(type(data_np))
# 2. 共享内存
data_tensor[1] = 4
data_np[2] = 6
print(data_tensor)
print(data_np)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2, 4, 6])
[2 4 6]


In [25]:
# 3. 规避共享内存
data_np = data_tensor.numpy().copy()
data_tensor[0] = 20
print(data_tensor)
print(data_np)

tensor([20,  4,  6])
[2 4 6]


### 3.2 numpy数组转换为张量
1. 使用torch.from_numpy()方法，默认共享内存，可以通过copy()函数规避
2. 使用torch.tensor()方法，默认不共享内存

In [27]:
# 1. from_numpy()
data_np = np.array([2, 3, 4])
data_tensor = torch.from_numpy(data_np)
data_np[1] = 4
data_tensor[2] = 6
print(data_tensor)
print(data_np)

tensor([2, 4, 6], dtype=torch.int32)
[2 4 6]


In [28]:
# 2. tensor()
data_np = np.array([2, 3, 4])
data_tensor = torch.tensor(data_np)
data_np[1] = 4
data_tensor[2] = 6
print(data_tensor)
print(data_np)

tensor([2, 3, 6], dtype=torch.int32)
[2 4 4]


### 3.3 标量张量和数字的转换

In [29]:
# 提取含有单个元素的张量的值: tensor.item()
tensor1 = torch.tensor(30)
tensor2 = torch.tensor([30])
tensor3 = torch.tensor([[30]])

print(tensor1.item())
print(tensor2.item())
print(tensor3.item())

30
30
30


## 4.张量的拼接

### 4.1 torch.cat()

In [30]:
torch.manual_seed(0)
data1 = torch.randint(0, 10, [3, 4, 5])
data2 = torch.randint(0, 10, [3, 4, 5])
print(data1.shape)
print(data2.shape)
# 1. 按0维度拼接
data = torch.cat([data1, data2], dim=0) # torch.cat(tensors, dim=dimension)
print(data.shape)
# 2. 按1维度拼接
data = torch.cat([data1, data2], dim=1)
print(data.shape)

torch.Size([3, 4, 5])
torch.Size([3, 4, 5])
torch.Size([6, 4, 5])
torch.Size([3, 8, 5])


### 4.2 torch.stack()

In [34]:
torch.manual_seed(0)
data1 = torch.randint(0, 10, [2, 3])
data2 = torch.randint(0, 10, [2, 3])
print(data1)
print(data2)
print('-' * 30)
# 将两个张量叠加(stack)
# 按0维度叠加(整体叠加)
data = torch.stack([data1, data2], dim=0)
print(data.shape)
print(data)
print('-' * 30)
# 按1维度叠加(按行叠加)
data = torch.stack([data1, data2], dim=1)
print(data.shape)
print(data)
print('-' * 30)
# 按2维度叠加(按元素叠加)
data = torch.stack([data1, data2], dim=2)
print(data.shape)
print(data)

tensor([[4, 9, 3],
        [0, 3, 9]])
tensor([[7, 3, 7],
        [3, 1, 6]])
------------------------------
torch.Size([2, 2, 3])
tensor([[[4, 9, 3],
         [0, 3, 9]],

        [[7, 3, 7],
         [3, 1, 6]]])
------------------------------
torch.Size([2, 2, 3])
tensor([[[4, 9, 3],
         [7, 3, 7]],

        [[0, 3, 9],
         [3, 1, 6]]])
------------------------------
torch.Size([2, 3, 2])
tensor([[[4, 7],
         [9, 3],
         [3, 7]],

        [[0, 3],
         [3, 1],
         [9, 6]]])


## 5.张量索引操作

### 5.1 简单行列索引

### 5.2 列表索引

### 5.3 范围索引

### 5.4 布尔索引

### 5.5 多维索引